# Generated by Django 5.0.6 on 2024-05-31 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('CR', 'CREATED'), ('CA', 'CANCELED'), ('CO', 'BEING COMPLETED'), ('SH', 'SHIPPED'), ('DE', 'DELIVERED')], default='CR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
